* Openroast

This is a fork of Openroast that adds an alternate requirements
file to install freshroastsr700 from my fork with a patch by
Github user [[http://github.com/trankin][trankin]] instead of from upstream.

This application cycles the heat setting on the roast between
low and high to maintain the temperature. Some units, for
whatever reason, don't understand it, and so just stay on high,
burning your coffee. With trankin's patch, it will cycle between
cool and high, instead.

See [[https://github.com/roastero/openroast][upstream repo]], and the Github [[https://github.com/Roastero/Openroast/issues/73][issue]] where this was discussed
and the solution shared by trankin [[https://github.com/trankin/Openroast/releases/tag/v1.2.1.1][here]]. Find the fork where I
applied trankin's patch [[https://github.com/tgdnt/freshroastsr700][here]]. His solution didn't include
installation instructions for Linux, and that is essentially
what I am providing here.

#+begin_src bash
git clone https://github.com/tgdnt/openroast
pip install -r openroast/build-with-freshroastsr700-cool.txt ./openroast
#+end_src

Consider installing this in a [[https://docs.python.org/3/library/venv.html][venv]] or [[https://virtualenv.pypa.io/en/stable/][virtualenv]], to avoid
changing you Python environment. Personally, I use
[[https://github.com/pyenv/pyenv-virtualenv][pyenv-virtualenv]]. Upstream indicates you should use Python
3.5.3, but it appears to work fine with Python 3.9.

** Installation on ArchLinux

If Openroast doesn't detect your roaster, try the instructions on
[[https://github.com/juliagoda/CH341SER][juliagoda/CH341SER]].
